[package]
name = "bento"
version = "0.1.0"
edition = "2024"
authors = ["00msjr"]
description = ""
license = "MIT"
repository = "https://github.com/00msjr/bento"

[dependencies]
clap = "4.0"
colored = "3.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.10"
